-- Generated by scripts/build_checks.py. New audit code; original SQL is unchanged.
CREATE TABLE audit_results (
  id int GENERATED ALWAYS AS IDENTITY,
  kind text NOT NULL, name text NOT NULL, verdict text NOT NULL, observed text NOT NULL
);
CREATE FUNCTION audit_assert(kind text, label text, ok boolean, details text)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO audit_results(kind,name,verdict,observed)
  VALUES(kind,label,CASE WHEN ok IS TRUE THEN 'PASS' ELSE 'FAIL' END,coalesce(details,'NULL'));
END $$;
CREATE FUNCTION audit_exec(kind text, label text, q text, expected_state text,
  expected_constraint text DEFAULT NULL, expected_rows bigint DEFAULT NULL, rollback_probe boolean DEFAULT false)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE actual_state text := '00000'; actual_constraint text := ''; affected bigint := 0; msg text := 'accepted';
BEGIN
  BEGIN
    EXECUTE q;
    GET DIAGNOSTICS affected = ROW_COUNT;
    IF rollback_probe THEN
      RAISE EXCEPTION USING ERRCODE='ZX001', MESSAGE='audit rollback probe';
    END IF;
  EXCEPTION
    WHEN SQLSTATE 'ZX001' THEN NULL;
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS actual_state = RETURNED_SQLSTATE,
        actual_constraint = CONSTRAINT_NAME, msg = MESSAGE_TEXT;
  END;
  PERFORM audit_assert(kind,label,
    actual_state = expected_state
    AND (expected_constraint IS NULL OR actual_constraint = expected_constraint)
    AND (expected_rows IS NULL OR affected = expected_rows),
    format('state=%s constraint=%s rows=%s %s',actual_state,actual_constraint,affected,msg));
END $$;


SELECT audit_assert('schema', '12 original domain tables', (SELECT count(*)=12 FROM information_schema.tables WHERE table_schema=current_schema() AND table_name<>'audit_results'), '12 tables, audit infrastructure excluded');

SELECT audit_assert('schema', 'all 38 columns and identity modes', NOT EXISTS (WITH expected(table_name,column_name,data_type,is_nullable,identity_generation) AS (VALUES ('role','id','integer','NO','ALWAYS'),
('role','name','character varying','NO',''),
('app_user','id','bigint','NO','ALWAYS'),
('app_user','role_id','integer','NO',''),
('app_user','email','character varying','NO',''),
('app_user','password_hash','character varying','NO',''),
('category','id','integer','NO','ALWAYS'),
('category','name','character varying','NO',''),
('news_source','id','integer','NO','ALWAYS'),
('news_source','name','character varying','NO',''),
('news_source','url','character varying','NO',''),
('news_source','status','character varying','NO',''),
('news','id','bigint','NO','ALWAYS'),
('news','source_id','integer','NO',''),
('news','canonical_url','character varying','NO',''),
('news','title','text','NO',''),
('news','content','text','YES',''),
('news','published_at','timestamp with time zone','NO',''),
('news_category','news_id','bigint','NO',''),
('news_category','category_id','integer','NO',''),
('subscription_category','user_id','bigint','NO',''),
('subscription_category','category_id','integer','NO',''),
('subscription_source','user_id','bigint','NO',''),
('subscription_source','source_id','integer','NO',''),
('favorite','user_id','bigint','NO',''),
('favorite','news_id','bigint','NO',''),
('scrape_run','id','bigint','NO','ALWAYS'),
('scrape_run','source_id','integer','NO',''),
('scrape_run','started_at','timestamp with time zone','NO',''),
('scrape_run','status','character varying','NO',''),
('import_result','id','bigint','NO','ALWAYS'),
('import_result','scrape_run_id','bigint','NO',''),
('import_result','news_id','bigint','YES',''),
('import_result','status','character varying','NO',''),
('scrape_error_log','id','bigint','NO','ALWAYS'),
('scrape_error_log','scrape_run_id','bigint','NO',''),
('scrape_error_log','error_message','text','NO',''),
('scrape_error_log','created_at','timestamp with time zone','NO','')) SELECT * FROM expected e FULL JOIN (SELECT table_name,column_name,data_type,is_nullable,coalesce(identity_generation,'') identity_generation FROM information_schema.columns WHERE table_schema=current_schema() AND table_name<>'audit_results') a USING(table_name,column_name) WHERE e.data_type IS DISTINCT FROM a.data_type OR e.is_nullable IS DISTINCT FROM a.is_nullable OR e.identity_generation IS DISTINCT FROM a.identity_generation), 'types, nullable and GENERATED ALWAYS modes match original schema');

SELECT audit_assert('schema', 'constraints p: 12', (SELECT count(*)=12 FROM pg_constraint WHERE connamespace=current_schema()::regnamespace AND contype='p'), 'catalog constraint type=p');

SELECT audit_assert('schema', 'constraints f: 14', (SELECT count(*)=14 FROM pg_constraint WHERE connamespace=current_schema()::regnamespace AND contype='f'), 'catalog constraint type=f');

SELECT audit_assert('schema', 'constraints u: 6', (SELECT count(*)=6 FROM pg_constraint WHERE connamespace=current_schema()::regnamespace AND contype='u'), 'catalog constraint type=u');

SELECT audit_assert('schema', 'constraints c: 4', (SELECT count(*)=4 FROM pg_constraint WHERE connamespace=current_schema()::regnamespace AND contype='c'), 'catalog constraint type=c');

SELECT audit_assert('schema', 'version 002 check is present', EXISTS(SELECT FROM pg_constraint WHERE conname='chk_scrape_run_status' AND connamespace=current_schema()::regnamespace), 'migration 002 applied');

SELECT audit_exec('source_replay', 'seed statement 01', 'INSERT INTO role (name) VALUES
(''Гость''),
(''Зарегистрированный пользователь''),
(''Администратор'')', '00000', NULL, NULL, false);

SELECT audit_exec('source_replay', 'seed statement 02', 'INSERT INTO app_user (role_id, email, password_hash) VALUES
(2, ''ivan.petrov@example.com'', ''pass_ivan123''),
(2, ''elena.sidorova@example.com'', ''elena_secure_2026''),
(3, ''admin.news@example.com'', ''super_admin_pass'')', '00000', NULL, NULL, false);

SELECT audit_exec('source_replay', 'seed statement 03', 'INSERT INTO app_user (role_id, email, password_hash) VALUES
(2, ''bigrussianboss@example.com'', ''brbrbr'')', '23514', 'app_user_password_hash_check', NULL, false);

SELECT audit_exec('source_replay', 'seed statement 04', 'INSERT INTO app_user (role_id, email, password_hash) VALUES
(2, ''elena.sidorova@example.com'', ''password'')', '23505', 'app_user_email_key', NULL, false);

SELECT audit_exec('source_replay', 'seed statement 05', 'INSERT INTO category (name) VALUES
(''Домашний''),
(''Спорт''),
(''Политика''),
(''Экономика''),
(''Без категории'')', '00000', NULL, NULL, false);

SELECT audit_exec('source_replay', 'seed statement 06', 'INSERT INTO news_source (name, url, status) VALUES
(''Бабушкины рецепты'', ''https://бабушкины-рецепты.рф/rss'', ''активен''),
(''Sport Express API'', ''https://sportexpress.example/api'', ''активен''),
(''Global News Feed'', ''https://globalnews.example/feed'', ''ошибка подключения''),
(''Old Archive Source'', ''https://oldarchive.example/rss'', ''отключён вручную''),
(''Unstable News Hub'', ''https://unstable.example/rss'', ''неактивен'')', '00000', NULL, NULL, false);

SELECT audit_exec('source_replay', 'seed statement 07', 'INSERT INTO scrape_run (source_id, started_at, status) VALUES
(1, NOW() - INTERVAL ''2 hour'', ''успешно завершен''),
(2, NOW() - INTERVAL ''1 hour'', ''успешно завершен''),
(3, NOW() - INTERVAL ''30 minutes'', ''ошибка подключения'')', '23514', 'chk_scrape_run_status', NULL, false);

SELECT audit_exec('source_replay', 'seed statement 08', 'INSERT INTO news (source_id, canonical_url, title, content, published_at) VALUES
(1, ''https://бабушкины-рецепты.рф/новости/рассолы'', ''Прорыв в сфере засолки огурцов'', ''Опубликованы новые данные по бабушкиным рецептам...'', NOW() - INTERVAL ''3 hour''),
(1, ''https://бабушкины-рецепты.рф/новости/лайфхаки'', ''100 заговоров для домохозяек'', ''Современные заговоры 2026...'', NOW() - INTERVAL ''2 hour''),
(2, ''https://sportexpress.example/news/champions-league'', ''Обзор матча Лиги Чемпионов'', ''Вчера состоялся яркий матч завершившегося тура...'', NOW() - INTERVAL ''1.5 hour''),
(3, ''https://globalnews.example/news/un-summit'', ''Срочные новости с саммита ООН'', ''Делегаты обсудили вопросы глобальной безопасности...'', NOW() - INTERVAL ''5 hour''),
(2, ''https://sportexpress.example/news/transfer-window'', ''Итоги зимнего трансферного окна'', ''Клубы завершили сделки на сумму...'', NOW() - INTERVAL ''30 minutes'')', '00000', NULL, NULL, false);

SELECT audit_exec('source_replay', 'seed statement 09', 'INSERT INTO news_category (news_id, category_id) VALUES
(1, 1),
(2, 1),
(3, 2),
(4, 3),
(4, 4),
(5, 2)', '00000', NULL, NULL, false);

SELECT audit_exec('source_replay', 'seed statement 10', 'INSERT INTO import_result (scrape_run_id, news_id, status) VALUES
(1, 1, ''успех''),
(1, 2, ''успех''),
(2, 3, ''успех''),
(2, 4, ''успех''),
(2, 5, ''успех'')', '23503', 'fk_import_run', NULL, false);

SELECT audit_exec('source_replay', 'seed statement 11', 'INSERT INTO import_result (scrape_run_id, news_id, status) VALUES
(1, NULL, ''дубликат'')', '23503', 'fk_import_run', NULL, false);

SELECT audit_exec('source_replay', 'seed statement 12', 'INSERT INTO scrape_error_log (scrape_run_id, error_message, created_at) VALUES
(3, ''Connection timeout: https://globalnews.example/feed :('', NOW() - INTERVAL ''30 minutes'')', '23503', 'fk_error_run', NULL, false);

SELECT audit_exec('source_replay', 'seed statement 13', 'INSERT INTO subscription_category (user_id, category_id) VALUES
(1, 1),
(1, 2),
(2, 3)', '00000', NULL, NULL, false);

SELECT audit_exec('source_replay', 'seed statement 14', 'INSERT INTO subscription_source (user_id, source_id) VALUES
(1, 1),
(2, 2)', '00000', NULL, NULL, false);

SELECT audit_exec('source_replay', 'seed statement 15', 'INSERT INTO favorite (user_id, news_id) VALUES
(1, 1),
(1, 3),
(2, 4)', '00000', NULL, NULL, false);

SELECT audit_assert('known_issue', 'seed has no scrape runs after v002', (SELECT count(*)=0 FROM scrape_run), 'invalid statuses reject the entire INSERT');

SELECT audit_assert('known_issue', 'seed has no imports and no error log', (SELECT count(*)=0 FROM import_result) AND (SELECT count(*)=0 FROM scrape_error_log), 'dependent rows rejected by FK after seed statuses fail');

SELECT audit_assert('known_issue', 'seed lacks canonical URL used by negative example 7.6', NOT EXISTS(SELECT FROM news WHERE canonical_url='https://example.com/news/123'), 'the original URL-negative example requires lifecycle 6.3 to run first');

SELECT audit_exec('source_replay', 'user scenario statement 1', 'INSERT INTO app_user (role_id, email, password_hash)
VALUES (
    2,
    ''new.user@example.com'',
    ''secure_password_123''
)
RETURNING id', '00000', NULL, 1, false);

SELECT audit_exec('source_replay', 'user scenario statement 2', 'UPDATE app_user
SET email = ''updated.user@example.com''
WHERE id = 4', '00000', NULL, 0, false);

SELECT audit_assert('known_issue', 'user created as id 6; UPDATE id 4 changes nothing', EXISTS(SELECT FROM app_user WHERE id=6 AND email='new.user@example.com') AND NOT EXISTS(SELECT FROM app_user WHERE email='updated.user@example.com'), 'two failed seed inserts consumed identity values 4 and 5');

SELECT audit_exec('source_replay', 'source scenario statement 1', 'INSERT INTO news_source (name, url, status)
VALUES (
    ''Example News'',
    ''https://example.com/rss'',
    ''активен''
)
RETURNING id', '00000', NULL, 1, false);

SELECT audit_exec('source_replay', 'source scenario statement 2', 'INSERT INTO scrape_run (source_id, started_at, status)
VALUES (
    1,
    CURRENT_TIMESTAMP,
    ''запущен''
)
RETURNING id', '00000', NULL, 1, false);

SELECT audit_exec('source_replay', 'source scenario statement 3', 'UPDATE scrape_run
SET status = ''завершен''
WHERE id = 1', '00000', NULL, 0, false);

SELECT audit_exec('source_replay', 'source scenario statement 4', 'INSERT INTO scrape_error_log (
    scrape_run_id,
    error_message
)
VALUES (
    1,
    ''Не удалось подключиться к источнику''
)', '23503', 'fk_error_run', NULL, false);

SELECT audit_exec('source_replay', 'source scenario statement 5', 'UPDATE scrape_run
SET status = ''ошибка''
WHERE id = 1', '00000', NULL, 0, false);

SELECT audit_assert('known_issue', 'new source 6 is not used by new run 2', EXISTS(SELECT FROM news_source WHERE id=6 AND name='Example News') AND EXISTS(SELECT FROM scrape_run WHERE id=2 AND source_id=1 AND status='запущен'), 'source_id=1 and WHERE id=1 ignore returned identifiers');

SELECT audit_exec('source_replay', 'news scenario statement 1', 'SELECT id
FROM news
WHERE canonical_url = ''https://example.com/news/123''', '00000', NULL, 0, false);

SELECT audit_exec('source_replay', 'news scenario statement 2', 'INSERT INTO news (
    source_id,
    canonical_url,
    title,
    content,
    published_at
)
VALUES (
    1,
    ''https://example.com/news/123'',
    ''Новая публикация'',
    ''Текст новости'',
    CURRENT_TIMESTAMP
)
RETURNING id', '00000', NULL, 1, false);

SELECT audit_exec('source_replay', 'news scenario statement 3', 'INSERT INTO import_result (
    scrape_run_id,
    news_id,
    status
)
VALUES (
    1,
    6,
    ''успех''
)', '23503', 'fk_import_run', NULL, false);

SELECT audit_assert('known_issue', 'news scenario creates uncategorized article 6', EXISTS(SELECT FROM news WHERE id=6) AND NOT EXISTS(SELECT FROM news_category WHERE news_id=6), 'no news_category statement in source lifecycle');

SELECT audit_exec('source_replay', '01_email_unique.sql after source scenarios', 'INSERT INTO app_user (role_id, email, password_hash)
VALUES (
    2,
    ''user@example.com'',
    ''another_password_hash''
)', '00000', NULL, NULL, true);

SELECT audit_exec('source_replay', '02_user_role_fk.sql after source scenarios', 'INSERT INTO app_user (role_id, email, password_hash)
VALUES (
    9999,
    ''new@example.com'',
    ''password_hash''
)', '23503', 'fk_user_role', NULL, true);

SELECT audit_exec('source_replay', '03_source_status_check.sql after source scenarios', 'INSERT INTO news_source (name, url, status)
VALUES (
    ''Test Source'',
    ''https://example.com/rss'',
    ''неизвестен''
)', '23514', 'news_source_status_check', NULL, true);

SELECT audit_exec('source_replay', '04_news_title_not_null.sql after source scenarios', 'INSERT INTO news (
    source_id,
    canonical_url,
    title,
    content,
    published_at
)
VALUES (
    1,
    ''https://example.com/news/999'',
    NULL,
    ''Текст новости'',
    CURRENT_TIMESTAMP
)', '23502', NULL, NULL, true);

SELECT audit_exec('source_replay', '05_news_source_fk.sql after source scenarios', 'INSERT INTO news (
    source_id,
    canonical_url,
    title,
    content,
    published_at
)
VALUES (
    9999,
    ''https://example.com/news/1000'',
    ''Тестовая новость'',
    ''Текст новости'',
    CURRENT_TIMESTAMP
)', '23503', 'fk_news_source', NULL, true);

SELECT audit_exec('source_replay', '06_news_url_unique.sql after source scenarios', 'INSERT INTO news (
    source_id,
    canonical_url,
    title,
    content,
    published_at
)
VALUES (
    1,
    ''https://example.com/news/123'',
    ''Другая версия новости'',
    ''Другой текст'',
    CURRENT_TIMESTAMP
)', '23505', 'news_canonical_url_key', NULL, true);

SELECT audit_assert('known_issue', 'original negative email precondition missing', NOT EXISTS(SELECT FROM app_user WHERE email='user@example.com'), 'negative 7.1 inserts a new email, not a duplicate');

SELECT audit_exec('constraint', 'create independent run fixture', 'INSERT INTO scrape_run(source_id,status) VALUES(1,''запущен'')', '00000', NULL, 1, false);

SELECT audit_exec('constraint', 'create independent imported-news fixture', 'INSERT INTO news(source_id,canonical_url,title,content,published_at) VALUES(1,''https://audit.example/fixture'',''Audit fixture'',''body'',now())', '00000', NULL, 1, false);

SELECT audit_exec('constraint', 'create independent successful-import fixture', 'INSERT INTO import_result(scrape_run_id,news_id,status) SELECT max(scrape_run.id),(SELECT id FROM news WHERE canonical_url=''https://audit.example/fixture''),''успех'' FROM scrape_run', '00000', NULL, 1, false);

SELECT audit_exec('constraint', 'unique real seed email', 'INSERT INTO app_user(role_id,email,password_hash) VALUES(2,''ivan.petrov@example.com'',''hash-long-enough'')', '23505', 'app_user_email_key', NULL, true);

SELECT audit_exec('constraint', 'user role FK', 'INSERT INTO app_user(role_id,email,password_hash) VALUES(9999,''audit@example.com'',''hash-long-enough'')', '23503', 'fk_user_role', NULL, true);

SELECT audit_exec('constraint', 'password hash length CHECK', 'INSERT INTO app_user(role_id,email,password_hash) VALUES(2,''audit@example.com'',''short'')', '23514', 'app_user_password_hash_check', NULL, true);

SELECT audit_exec('constraint', 'source status CHECK', 'INSERT INTO news_source(name,url,status) VALUES(''audit'',''https://audit.example/rss'',''invalid'')', '23514', 'news_source_status_check', NULL, true);

SELECT audit_exec('constraint', 'run status CHECK', 'INSERT INTO scrape_run(source_id,status) VALUES(1,''успешно завершен'')', '23514', 'chk_scrape_run_status', NULL, true);

SELECT audit_exec('constraint', 'news title NOT NULL', 'INSERT INTO news(source_id,canonical_url,title,published_at) VALUES(1,''https://audit.example/no-title'',NULL,now())', '23502', NULL, NULL, true);

SELECT audit_exec('constraint', 'news source FK', 'INSERT INTO news(source_id,canonical_url,title,published_at) VALUES(9999,''https://audit.example/no-source'',''test'',now())', '23503', 'fk_news_source', NULL, true);

SELECT audit_exec('constraint', 'canonical URL UNIQUE', 'INSERT INTO news(source_id,canonical_url,title,published_at) VALUES(1,''https://audit.example/fixture'',''test'',now())', '23505', 'news_canonical_url_key', NULL, true);

SELECT audit_exec('constraint', 'source URL UNIQUE', 'INSERT INTO news_source(name,url) SELECT ''audit'',url FROM news_source WHERE id=1', '23505', 'news_source_url_key', NULL, true);

SELECT audit_exec('constraint', 'category subscription PK', 'INSERT INTO subscription_category VALUES(1,1)', '23505', 'subscription_category_pkey', NULL, true);

SELECT audit_exec('constraint', 'source subscription PK', 'INSERT INTO subscription_source VALUES(1,1)', '23505', 'subscription_source_pkey', NULL, true);

SELECT audit_exec('constraint', 'favorite PK', 'INSERT INTO favorite VALUES(1,1)', '23505', 'favorite_pkey', NULL, true);

SELECT audit_exec('constraint', 'import status CHECK', 'INSERT INTO import_result(scrape_run_id,status) SELECT max(id),''invalid'' FROM scrape_run', '23514', 'import_result_status_check', NULL, true);

SELECT audit_exec('constraint', 'created-news import UNIQUE', 'INSERT INTO import_result(scrape_run_id,news_id,status) SELECT max(scrape_run.id),(SELECT id FROM news WHERE canonical_url=''https://audit.example/fixture''),''успех'' FROM scrape_run', '23505', 'import_result_news_id_key', NULL, true);

SELECT audit_exec('known_issue', 'news can be committed without any category', 'INSERT INTO news(source_id,canonical_url,title,published_at) VALUES(1,''https://audit.example/no-category'',''test'',now())', '00000', NULL, 1, true);

SELECT audit_exec('known_issue', 'news can have NULL content', 'INSERT INTO news(source_id,canonical_url,title,content,published_at) VALUES(1,''https://audit.example/no-content'',''test'',NULL,now())', '00000', NULL, 1, true);

SELECT audit_exec('known_issue', 'successful import can have NULL news_id', 'INSERT INTO import_result(scrape_run_id,status) SELECT max(id),''успех'' FROM scrape_run', '00000', NULL, 1, true);

SELECT audit_exec('known_issue', 'error import can link to created news', 'INSERT INTO import_result(scrape_run_id,news_id,status) SELECT max(scrape_run.id),6,''ошибка'' FROM scrape_run', '00000', NULL, 1, true);

SELECT audit_exec('known_issue', 'run and imported article can have different sources', 'INSERT INTO import_result(scrape_run_id,news_id,status) SELECT max(scrape_run.id),4,''успех'' FROM scrape_run', '00000', NULL, 1, true);

SELECT audit_exec('known_issue', 'subscription to inactive source is accepted', 'INSERT INTO subscription_source VALUES(1,5)', '00000', NULL, 1, true);

SELECT audit_exec('known_issue', 'subscription to service category is accepted', 'INSERT INTO subscription_category VALUES(1,5)', '00000', NULL, 1, true);

SELECT audit_exec('known_issue', 'empty title and canonical URL are accepted', 'INSERT INTO news(source_id,canonical_url,title,published_at) VALUES(1,'''','''',now())', '00000', NULL, 1, true);

SELECT audit_exec('known_issue', 'invalid email format is accepted', 'INSERT INTO app_user(role_id,email,password_hash) VALUES(2,''not-an-email'',''hash-long-enough'')', '00000', NULL, 1, true);

SELECT audit_exec('known_issue', 'case variant of existing email is accepted', 'INSERT INTO app_user(role_id,email,password_hash) VALUES(2,''IVAN.PETROV@example.com'',''hash-long-enough'')', '00000', NULL, 1, true);

SELECT audit_exec('known_issue', 'run terminal status can return to running', 'DO $p$ BEGIN
      UPDATE scrape_run SET status=''завершен'' WHERE id=(SELECT max(id) FROM scrape_run);
      UPDATE scrape_run SET status=''запущен'' WHERE id=(SELECT max(id) FROM scrape_run);
      IF (SELECT status FROM scrape_run ORDER BY id DESC LIMIT 1) <> ''запущен'' THEN
        RAISE EXCEPTION ''unexpected state transition guard'';
      END IF;
    END $p$', '00000', NULL, NULL, true);

SELECT audit_exec('known_issue', 'deleting last category removes only assignment, keeps article', 'DO $p$ BEGIN
      DELETE FROM category WHERE id=1;
      IF NOT EXISTS(SELECT FROM news WHERE id=1) OR EXISTS(SELECT FROM news_category WHERE news_id=1) THEN
        RAISE EXCEPTION ''unexpected deletion behavior'';
      END IF;
    END $p$', '00000', NULL, NULL, true);

SELECT audit_exec('known_issue', 'deleting source cascades into saved news, favorites, runs and subscriptions', 'DO $p$ BEGIN
      DELETE FROM news_source WHERE id=1;
      IF EXISTS(SELECT FROM news WHERE id=1) OR EXISTS(SELECT FROM favorite WHERE news_id=1)
         OR EXISTS(SELECT FROM subscription_source WHERE source_id=1)
         OR EXISTS(SELECT FROM scrape_run WHERE source_id=1) THEN
        RAISE EXCEPTION ''unexpected cascade behavior'';
      END IF;
    END $p$', '00000', NULL, NULL, true);

SELECT audit_exec('known_issue', 'source can be disabled but a run can still be inserted', 'INSERT INTO scrape_run(source_id,status) VALUES(4,''запущен'')', '00000', NULL, 1, true);

SELECT audit_exec('known_issue', 'three failed runs do not update source status', 'DO $p$ BEGIN
      INSERT INTO scrape_run(source_id,status) VALUES(2,''ошибка''),(2,''ошибка''),(2,''ошибка'');
      IF (SELECT status FROM news_source WHERE id=2) <> ''активен'' THEN
        RAISE EXCEPTION ''unexpected automatic state change'';
      END IF;
    END $p$', '00000', NULL, NULL, true);

\ir ../migrations/002_add_scrape_run_status_check.down.sql

SELECT audit_assert('schema', 'migration 002 down removes only status CHECK', NOT EXISTS(SELECT FROM pg_constraint WHERE conname='chk_scrape_run_status' AND connamespace=current_schema()::regnamespace), 'version 001 state restored');

\ir ../migrations/002_add_scrape_run_status_check.up.sql

SELECT audit_assert('schema', 'migration 002 reapplies with valid audit data', EXISTS(SELECT FROM pg_constraint WHERE conname='chk_scrape_run_status' AND connamespace=current_schema()::regnamespace), 'up/down/up works when existing statuses are valid');

\ir ../migrations/002_add_scrape_run_status_check.down.sql

SELECT audit_exec('source_replay', 'v001 accepts original run seed statuses', 'INSERT INTO scrape_run (source_id, started_at, status) VALUES
(1, NOW() - INTERVAL ''2 hour'', ''успешно завершен''),
(2, NOW() - INTERVAL ''1 hour'', ''успешно завершен''),
(3, NOW() - INTERVAL ''30 minutes'', ''ошибка подключения'')', '00000', NULL, 3, false);

SELECT audit_exec('known_issue', 'upgrading v001 populated with report statuses fails', 'ALTER TABLE scrape_run
ADD CONSTRAINT chk_scrape_run_status CHECK (status IN (''запущен'', ''завершен'', ''ошибка''));
', '23514', 'chk_scrape_run_status', NULL, false);

\ir ../migrations/001_init.down.sql

SELECT audit_assert('schema', 'migration 001 down removes all domain tables', (SELECT count(*)=0 FROM information_schema.tables WHERE table_schema=current_schema() AND table_name<>'audit_results'), 'down migration dependency order works');

\ir ../migrations/001_init.up.sql

\ir ../migrations/002_add_scrape_run_status_check.up.sql

SELECT audit_assert('schema', 'fresh schema recreated after complete rollback', (SELECT count(*)=12 FROM information_schema.tables WHERE table_schema=current_schema() AND table_name<>'audit_results'), 'all domain tables recreated');
