#!/usr/bin/env python3
"""Build audit expectations for unchanged SQL; does not repair the project."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def literal(s):
    return "'" + s.replace("'", "''") + "'"


def statements(path):
    # These particular report listings contain no semicolons inside literals.
    text = (ROOT/path).read_text()
    text = '\n'.join(line.split('--', 1)[0].rstrip() for line in text.splitlines())
    return [s.strip() for s in text.split(';') if s.strip()]


def build():
    lines = ["""-- Generated by scripts/build_checks.py. New audit code; original SQL is unchanged.
CREATE TABLE audit_results (
  id int GENERATED ALWAYS AS IDENTITY,
  kind text NOT NULL, name text NOT NULL, verdict text NOT NULL, observed text NOT NULL
);
CREATE FUNCTION audit_assert(kind text, label text, ok boolean, details text)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO audit_results(kind,name,verdict,observed)
  VALUES(kind,label,CASE WHEN ok IS TRUE THEN 'PASS' ELSE 'FAIL' END,coalesce(details,'NULL'));
END $$;
CREATE FUNCTION audit_exec(kind text, label text, q text, expected_state text,
  expected_constraint text DEFAULT NULL, expected_rows bigint DEFAULT NULL, rollback_probe boolean DEFAULT false)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE actual_state text := '00000'; actual_constraint text := ''; affected bigint := 0; msg text := 'accepted';
BEGIN
  BEGIN
    EXECUTE q;
    GET DIAGNOSTICS affected = ROW_COUNT;
    IF rollback_probe THEN
      RAISE EXCEPTION USING ERRCODE='ZX001', MESSAGE='audit rollback probe';
    END IF;
  EXCEPTION
    WHEN SQLSTATE 'ZX001' THEN NULL;
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS actual_state = RETURNED_SQLSTATE,
        actual_constraint = CONSTRAINT_NAME, msg = MESSAGE_TEXT;
  END;
  PERFORM audit_assert(kind,label,
    actual_state = expected_state
    AND (expected_constraint IS NULL OR actual_constraint = expected_constraint)
    AND (expected_rows IS NULL OR affected = expected_rows),
    format('state=%s constraint=%s rows=%s %s',actual_state,actual_constraint,affected,msg));
END $$;
"""]
    def assertion(kind,name,condition,details):
        lines.append(f"SELECT audit_assert({literal(kind)}, {literal(name)}, {condition}, {literal(details)});")
    def execute(kind,name,q,state='00000',constraint=None,rows=None,probe=False):
        lines.append('SELECT audit_exec('+', '.join([literal(kind),literal(name),literal(q),literal(state),
                     'NULL' if constraint is None else literal(constraint),
                     'NULL' if rows is None else str(rows),'true' if probe else 'false'])+');')

    assertion('schema','12 original domain tables',
              "(SELECT count(*)=12 FROM information_schema.tables WHERE table_schema=current_schema() AND table_name<>'audit_results')",
              '12 tables, audit infrastructure excluded')
    columns = {
      'role': [('id','integer','NO','ALWAYS'),('name','character varying','NO','')],
      'app_user': [('id','bigint','NO','ALWAYS'),('role_id','integer','NO',''),('email','character varying','NO',''),('password_hash','character varying','NO','')],
      'category': [('id','integer','NO','ALWAYS'),('name','character varying','NO','')],
      'news_source': [('id','integer','NO','ALWAYS'),('name','character varying','NO',''),('url','character varying','NO',''),('status','character varying','NO','')],
      'news': [('id','bigint','NO','ALWAYS'),('source_id','integer','NO',''),('canonical_url','character varying','NO',''),('title','text','NO',''),('content','text','YES',''),('published_at','timestamp with time zone','NO','')],
      'news_category': [('news_id','bigint','NO',''),('category_id','integer','NO','')],
      'subscription_category': [('user_id','bigint','NO',''),('category_id','integer','NO','')],
      'subscription_source': [('user_id','bigint','NO',''),('source_id','integer','NO','')],
      'favorite': [('user_id','bigint','NO',''),('news_id','bigint','NO','')],
      'scrape_run': [('id','bigint','NO','ALWAYS'),('source_id','integer','NO',''),('started_at','timestamp with time zone','NO',''),('status','character varying','NO','')],
      'import_result': [('id','bigint','NO','ALWAYS'),('scrape_run_id','bigint','NO',''),('news_id','bigint','YES',''),('status','character varying','NO','')],
      'scrape_error_log': [('id','bigint','NO','ALWAYS'),('scrape_run_id','bigint','NO',''),('error_message','text','NO',''),('created_at','timestamp with time zone','NO','')]
    }
    vals = ',\n'.join('('+','.join(literal(v) for v in (table,*col))+')' for table,cols in columns.items() for col in cols)
    assertion('schema','all 38 columns and identity modes',
      f"NOT EXISTS (WITH expected(table_name,column_name,data_type,is_nullable,identity_generation) AS (VALUES {vals}) SELECT * FROM expected e FULL JOIN (SELECT table_name,column_name,data_type,is_nullable,coalesce(identity_generation,'') identity_generation FROM information_schema.columns WHERE table_schema=current_schema() AND table_name<>'audit_results') a USING(table_name,column_name) WHERE e.data_type IS DISTINCT FROM a.data_type OR e.is_nullable IS DISTINCT FROM a.is_nullable OR e.identity_generation IS DISTINCT FROM a.identity_generation)",
      'types, nullable and GENERATED ALWAYS modes match original schema')
    for typ,num in [('p',12),('f',14),('u',6),('c',4)]:
        assertion('schema',f'constraints {typ}: {num}',
          f"(SELECT count(*)={num} FROM pg_constraint WHERE connamespace=current_schema()::regnamespace AND contype='{typ}')",f'catalog constraint type={typ}')
    assertion('schema','version 002 check is present',
              "EXISTS(SELECT FROM pg_constraint WHERE conname='chk_scrape_run_status' AND connamespace=current_schema()::regnamespace)",'migration 002 applied')

    seed = statements('sql/seed/report_test.sql')
    expected = {3:('23514','app_user_password_hash_check'),4:('23505','app_user_email_key'),
                7:('23514','chk_scrape_run_status'),10:('23503','fk_import_run'),
                11:('23503','fk_import_run'),12:('23503','fk_error_run')}
    for n,q in enumerate(seed,1):
        state,con = expected.get(n,('00000',None))
        execute('source_replay',f'seed statement {n:02d}',q,state,con)
    assertion('known_issue','seed has no scrape runs after v002',
              '(SELECT count(*)=0 FROM scrape_run)','invalid statuses reject the entire INSERT')
    assertion('known_issue','seed has no imports and no error log',
              '(SELECT count(*)=0 FROM import_result) AND (SELECT count(*)=0 FROM scrape_error_log)',
              'dependent rows rejected by FK after seed statuses fail')
    assertion('known_issue','seed lacks canonical URL used by negative example 7.6',
              "NOT EXISTS(SELECT FROM news WHERE canonical_url='https://example.com/news/123')",
              'the original URL-negative example requires lifecycle 6.3 to run first')

    for n,q in enumerate(statements('sql/scenarios/01_user.sql'),1):
        execute('source_replay',f'user scenario statement {n}',q,rows=1 if n==1 else 0)
    assertion('known_issue','user created as id 6; UPDATE id 4 changes nothing',
              "EXISTS(SELECT FROM app_user WHERE id=6 AND email='new.user@example.com') AND NOT EXISTS(SELECT FROM app_user WHERE email='updated.user@example.com')",
              'two failed seed inserts consumed identity values 4 and 5')
    for n,q in enumerate(statements('sql/scenarios/02_source.sql'),1):
        execute('source_replay',f'source scenario statement {n}',q,
                '23503' if n==4 else '00000','fk_error_run' if n==4 else None,
                rows=None if n==4 else (1 if n<=2 else 0))
    assertion('known_issue','new source 6 is not used by new run 2',
              "EXISTS(SELECT FROM news_source WHERE id=6 AND name='Example News') AND EXISTS(SELECT FROM scrape_run WHERE id=2 AND source_id=1 AND status='запущен')",
              'source_id=1 and WHERE id=1 ignore returned identifiers')
    for n,q in enumerate(statements('sql/scenarios/03_news.sql'),1):
        execute('source_replay',f'news scenario statement {n}',q,
                '23503' if n==3 else '00000','fk_import_run' if n==3 else None,
                rows=0 if n==1 else (1 if n==2 else None))
    assertion('known_issue','news scenario creates uncategorized article 6',
              "EXISTS(SELECT FROM news WHERE id=6) AND NOT EXISTS(SELECT FROM news_category WHERE news_id=6)",
              'no news_category statement in source lifecycle')

    negative = sorted((ROOT/'sql/negative').glob('*.sql'))
    states = [('00000',None),('23503','fk_user_role'),('23514','news_source_status_check'),
              ('23502',None),('23503','fk_news_source'),('23505','news_canonical_url_key')]
    for path,(state,con) in zip(negative,states):
        execute('source_replay',path.name+' after source scenarios',statements(path.relative_to(ROOT))[0],state,con,probe=True)
    assertion('known_issue','original negative email precondition missing',
              "NOT EXISTS(SELECT FROM app_user WHERE email='user@example.com')",'negative 7.1 inserts a new email, not a duplicate')
    # New fixtures, isolated from report data; use returned identities via subqueries.
    execute('constraint','create independent run fixture',
            "INSERT INTO scrape_run(source_id,status) VALUES(1,'запущен')",rows=1)
    execute('constraint','create independent imported-news fixture',
            "INSERT INTO news(source_id,canonical_url,title,content,published_at) VALUES(1,'https://audit.example/fixture','Audit fixture','body',now())",rows=1)
    execute('constraint','create independent successful-import fixture',
            "INSERT INTO import_result(scrape_run_id,news_id,status) SELECT max(scrape_run.id),(SELECT id FROM news WHERE canonical_url='https://audit.example/fixture'),'успех' FROM scrape_run",rows=1)
    fixtures = [
      ('unique real seed email',"INSERT INTO app_user(role_id,email,password_hash) VALUES(2,'ivan.petrov@example.com','hash-long-enough')",'23505','app_user_email_key'),
      ('user role FK',"INSERT INTO app_user(role_id,email,password_hash) VALUES(9999,'audit@example.com','hash-long-enough')",'23503','fk_user_role'),
      ('password hash length CHECK',"INSERT INTO app_user(role_id,email,password_hash) VALUES(2,'audit@example.com','short')",'23514','app_user_password_hash_check'),
      ('source status CHECK',"INSERT INTO news_source(name,url,status) VALUES('audit','https://audit.example/rss','invalid')",'23514','news_source_status_check'),
      ('run status CHECK',"INSERT INTO scrape_run(source_id,status) VALUES(1,'успешно завершен')",'23514','chk_scrape_run_status'),
      ('news title NOT NULL',"INSERT INTO news(source_id,canonical_url,title,published_at) VALUES(1,'https://audit.example/no-title',NULL,now())",'23502',None),
      ('news source FK',"INSERT INTO news(source_id,canonical_url,title,published_at) VALUES(9999,'https://audit.example/no-source','test',now())",'23503','fk_news_source'),
      ('canonical URL UNIQUE',"INSERT INTO news(source_id,canonical_url,title,published_at) VALUES(1,'https://audit.example/fixture','test',now())",'23505','news_canonical_url_key'),
      ('source URL UNIQUE',"INSERT INTO news_source(name,url) SELECT 'audit',url FROM news_source WHERE id=1",'23505','news_source_url_key'),
      ('category subscription PK',"INSERT INTO subscription_category VALUES(1,1)",'23505','subscription_category_pkey'),
      ('source subscription PK',"INSERT INTO subscription_source VALUES(1,1)",'23505','subscription_source_pkey'),
      ('favorite PK',"INSERT INTO favorite VALUES(1,1)",'23505','favorite_pkey'),
      ('import status CHECK',"INSERT INTO import_result(scrape_run_id,status) SELECT max(id),'invalid' FROM scrape_run",'23514','import_result_status_check'),
      ('created-news import UNIQUE',"INSERT INTO import_result(scrape_run_id,news_id,status) SELECT max(scrape_run.id),(SELECT id FROM news WHERE canonical_url='https://audit.example/fixture'),'успех' FROM scrape_run",'23505','import_result_news_id_key'),
    ]
    for name,q,state,con in fixtures:
        execute('constraint',name,q,state,con,probe=True)
    probes = [
      ('news can be committed without any category',"INSERT INTO news(source_id,canonical_url,title,published_at) VALUES(1,'https://audit.example/no-category','test',now())"),
      ('news can have NULL content',"INSERT INTO news(source_id,canonical_url,title,content,published_at) VALUES(1,'https://audit.example/no-content','test',NULL,now())"),
      ('successful import can have NULL news_id',"INSERT INTO import_result(scrape_run_id,status) SELECT max(id),'успех' FROM scrape_run"),
      ('error import can link to created news',"INSERT INTO import_result(scrape_run_id,news_id,status) SELECT max(scrape_run.id),6,'ошибка' FROM scrape_run"),
      ('run and imported article can have different sources',"INSERT INTO import_result(scrape_run_id,news_id,status) SELECT max(scrape_run.id),4,'успех' FROM scrape_run"),
      ('subscription to inactive source is accepted',"INSERT INTO subscription_source VALUES(1,5)"),
      ('subscription to service category is accepted',"INSERT INTO subscription_category VALUES(1,5)"),
      ('empty title and canonical URL are accepted',"INSERT INTO news(source_id,canonical_url,title,published_at) VALUES(1,'','',now())"),
      ('invalid email format is accepted',"INSERT INTO app_user(role_id,email,password_hash) VALUES(2,'not-an-email','hash-long-enough')"),
      ('case variant of existing email is accepted',"INSERT INTO app_user(role_id,email,password_hash) VALUES(2,'IVAN.PETROV@example.com','hash-long-enough')"),
    ]
    for name,q in probes:
        execute('known_issue',name,q,rows=1,probe=True)
    execute('known_issue','run terminal status can return to running',"""DO $p$ BEGIN
      UPDATE scrape_run SET status='завершен' WHERE id=(SELECT max(id) FROM scrape_run);
      UPDATE scrape_run SET status='запущен' WHERE id=(SELECT max(id) FROM scrape_run);
      IF (SELECT status FROM scrape_run ORDER BY id DESC LIMIT 1) <> 'запущен' THEN
        RAISE EXCEPTION 'unexpected state transition guard';
      END IF;
    END $p$""",probe=True)
    execute('known_issue','deleting last category removes only assignment, keeps article',"""DO $p$ BEGIN
      DELETE FROM category WHERE id=1;
      IF NOT EXISTS(SELECT FROM news WHERE id=1) OR EXISTS(SELECT FROM news_category WHERE news_id=1) THEN
        RAISE EXCEPTION 'unexpected deletion behavior';
      END IF;
    END $p$""",probe=True)
    execute('known_issue','deleting source cascades into saved news, favorites, runs and subscriptions',"""DO $p$ BEGIN
      DELETE FROM news_source WHERE id=1;
      IF EXISTS(SELECT FROM news WHERE id=1) OR EXISTS(SELECT FROM favorite WHERE news_id=1)
         OR EXISTS(SELECT FROM subscription_source WHERE source_id=1)
         OR EXISTS(SELECT FROM scrape_run WHERE source_id=1) THEN
        RAISE EXCEPTION 'unexpected cascade behavior';
      END IF;
    END $p$""",probe=True)
    execute('known_issue','source can be disabled but a run can still be inserted',
            "INSERT INTO scrape_run(source_id,status) VALUES(4,'запущен')",probe=True,rows=1)
    execute('known_issue','three failed runs do not update source status',"""DO $p$ BEGIN
      INSERT INTO scrape_run(source_id,status) VALUES(2,'ошибка'),(2,'ошибка'),(2,'ошибка');
      IF (SELECT status FROM news_source WHERE id=2) <> 'активен' THEN
        RAISE EXCEPTION 'unexpected automatic state change';
      END IF;
    END $p$""",probe=True)
    # Check reversible schema migration and compatibility with v001 data separately.
    lines += ["\\ir ../migrations/002_add_scrape_run_status_check.down.sql"]
    assertion('schema','migration 002 down removes only status CHECK',
              "NOT EXISTS(SELECT FROM pg_constraint WHERE conname='chk_scrape_run_status' AND connamespace=current_schema()::regnamespace)",'version 001 state restored')
    lines += ["\\ir ../migrations/002_add_scrape_run_status_check.up.sql"]
    assertion('schema','migration 002 reapplies with valid audit data',
              "EXISTS(SELECT FROM pg_constraint WHERE conname='chk_scrape_run_status' AND connamespace=current_schema()::regnamespace)",'up/down/up works when existing statuses are valid')
    lines += ["\\ir ../migrations/002_add_scrape_run_status_check.down.sql"]
    execute('source_replay','v001 accepts original run seed statuses',seed[6],rows=3)
    execute('known_issue','upgrading v001 populated with report statuses fails',
            (ROOT/'migrations/002_add_scrape_run_status_check.up.sql').read_text(),'23514','chk_scrape_run_status')
    lines += ["\\ir ../migrations/001_init.down.sql"]
    assertion('schema','migration 001 down removes all domain tables',
              "(SELECT count(*)=0 FROM information_schema.tables WHERE table_schema=current_schema() AND table_name<>'audit_results')",'down migration dependency order works')
    lines += ["\\ir ../migrations/001_init.up.sql", "\\ir ../migrations/002_add_scrape_run_status_check.up.sql"]
    assertion('schema','fresh schema recreated after complete rollback',
              "(SELECT count(*)=12 FROM information_schema.tables WHERE table_schema=current_schema() AND table_name<>'audit_results')",'all domain tables recreated')
    return '\n\n'.join(lines)+'\n'


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    data=build()
    dest=ROOT/'tests/checks.sql'
    if args.check:
        if dest.read_text()!=data:
            raise SystemExit('FAIL: generated checks differ; run scripts/build_checks.py')
        print('PASS: generated checks match source listings and expectations')
    else:
        dest.write_text(data)
        print('Created tests/checks.sql')
